### ISSUE TITLE
csv reports with delimiter ","

### ISSUE THREAD

**Issue by GD-Aichi** [bhushankumarl/amazon-mws#22]
error in  reports with delimiter "," for example _SC_VAT_TAX_REPORT_ .
report _GET_VAT_TRANSACTION_DATA_ work fine, but this report has delimiter "\t".

**Comment by bhushankumarl** [comment]
@GD-Aichi Would you provide which API example which you are trying to use?

**Comment by GD-Aichi** [comment]
[Tax Reports - Amazon VAT Calculation Report](http://docs.developer.amazonservices.com/en_DE/reports/Reports_ReportType.html#ReportTypeCategories__SalesTaxReports).
> Comma-separated flat file report 
```
const response = await amazonMws.reports.search({
     'Version': '2009-01-01',
     'Action': 'GetReport',
     'SellerId': SELLER_ID,
     'MWSAuthToken': MWS_AUTH_TOKEN,
    'ReportId': 'XXXXXXXX', 
});
```

**Comment by bhushankumarl** [comment]
@GD-Aichi and which kind of error do you face?

**Comment by GD-Aichi** [comment]
Oh sorry.
```
/###/node_modules/fast-csv/lib/parser/parser.js:80
            throw new Error("Parse Error: expected: '" + ESCAPE + "' got: '" + nextToken + "'. at '" + str.substr(cursor, 10).replace(/[\r\n]/g, "\\n" + "'"));
                  ^
Error: Parse Error: expected: '"' got: ','. at ',"Merchant
    at parseEscapedItem (/###/node_modules/fast-csv/lib/parser/parser.js:80:19)
    at ParserStream.parseLine [as parser] (/###/node_modules/fast-csv/lib/parser/parser.js:192:30)
    at ParserStream._parseLine [as _parse] (/###/node_modules/fast-csv/lib/parser/parser_stream.js:178:25)
    at ParserStream._transform (/###/node_modules/fast-csv/lib/parser/parser_stream.js:221:18)
    at ParserStream.Transform._read (_stream_transform.js:185:10)
    at ParserStream.Transform._write (_stream_transform.js:173:12)
    at doWrite (_stream_writable.js:406:12)
    at writeOrBuffer (_stream_writable.js:392:5)
    at ParserStream.Writable.write (_stream_writable.js:290:11)
    at Readable.ondata (_stream_readable.js:646:20)
    at Readable.emit (events.js:127:13)
    at Readable.emit (domain.js:421:20)
    at Readable.read (_stream_readable.js:482:10)
    at flow (_stream_readable.js:853:34)
    at emitReadable_ (_stream_readable.js:521:3)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by bhushankumarl** [comment]
@GD-Aichi 
The error seems to come from the 'fast-csv' package. Not from this library.

Also, We support only JSON responses. So, if you log the immediate response receive from the ``` amazonMws.reports.search ``` you will found array of JSON.

**Comment by GD-Aichi** [comment]
Yes the error come from 'fast-csv', but the problem is the wrong delimiter of response file.
https://github.com/bhushankumarl/amazon-mws/blob/master/lib/AmazonMwsResource.js#L173

**Comment by bhushankumarl** [comment]
@GD-Aichi Can you send me an entire stack of the error?

**Comment by GD-Aichi** [comment]
If I change the delimiter from '\t'  to ',' then it will working.
https://github.com/bhushankumarl/amazon-mws/blob/99440103b315eed0fda333306c940c8bef67bae6/lib/AmazonMwsResource.js#L173
It that posible in the api?
```js
const response = await amazonMws.reports.search({
     'Version': '2009-01-01',
     'Action': 'GetReport',
     'SellerId': SELLER_ID,
     'MWSAuthToken': MWS_AUTH_TOKEN,
     'ReportId': 'XXXXXXXX', 
     'delimiter': ','
});
```

**Comment by bhushankumarl** [comment]
@GD-Aichi 
Other files have delimiter as `,`. So I need something which can identify the string response whether it is comma delimited or tab delimited.

**Comment by GD-Aichi** [comment]
The header send nothing, is delimiter ```,``` or ```\t```.
```js
const delimiter = ['\t', ','];
let count = 0;
let doIt = true;
do {
  let data = [];
  try {
                csv.fromString(response, {headers: true, delimiter: delimiter[count]})
                  .on('data', function (value) {
                      data.push(value);
                  })
                  .on('end', function () {
                      debug('response after parsing tab delimited file %o ', data);
                      response = {};
                      response.data = data;
                      response.Headers = {
                          'x-mws-quota-max': res.headers['x-mws-quota-max'] || 'unknown',
                          'x-mws-quota-remaining': res.headers['x-mws-quota-remaining'] || 'unknown',
                          'x-mws-quota-resetson': res.headers['x-mws-quota-resetson'] || 'unknown',
                          'x-mws-timestamp': res.headers['x-mws-timestamp']
                      };
                      return callback(null, response);
                  });
     doIt = false;
  } catch(err) {
    count++;
    data = [];
  }
} while (doIt);
```
You may be able to use this to solve the problem.

**Comment by bhushankumarl** [comment]
@GD-Aichi 
I am working on it. We'll provide you the solution soon.

**Comment by bhushankumarl** [comment]
@GD-Aichi 
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.16

Solved, released new version. Please, verify and let me know.

**Comment by GD-Aichi** [comment]
Version 0.0.16 don't work. You use try-catch outside the callback function.
This work for me.
```js
 } else {
                debug('It is NON-XML Response');
                const TAB_DELIMITER = '\t';
                const COMMA_DELIMITER = ',';

                parseCSVFile(res, responseString, TAB_DELIMITER, (err, items) => {
                    if (!err) {
                        return callback(null, items);
                    }
                    debug('It is TAB_DELIMITER Exception ', err);
                        debug('Let us try to delimit using COMMA_DELIMITER');
                        parseCSVFile(res, responseString, COMMA_DELIMITER, (error, items) => {
                            if (error) {
                                debug('It is COMMA_DELIMITER Exception ', Exception);
                                debug('Parsing using both TAB_DELIMITER & COMMA_DELIMITER Failed.');
                                debug('It may due to empty response or invalid request.');
                                return callback(new Error('Parsing fail.'));
                            }
                            console.log()
                            return callback(null, items);
                        });
                });


 }
```

**Comment by bhushankumarl** [comment]
Well. As per discussion correction made.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.17
