### ISSUE TITLE
"500 - Server Error" response from MWS crashes Node

### ISSUE THREAD

**Issue by colinskow** [bhushankumarl/amazon-mws#47]
Occasionally MWS is spitting back this in response to an otherwise correct request:

```xml
<?xml version="1.0"?>
<ErrorResponse>
    <Error>
        <Type>Server</Type>
        <Code>500</Code>
        <Message>500 - Server Error</Message>
        <Detail />
    </Error>
</ErrorResponse>
```

In that case this library crashes with this error message, instead of returning proper error JSON:

```
 { Error: Invalid JSON received from the AmazonMws API
    at Constructor._Error (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/Error.js:12:19)
    at Constructor (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/utils.js:85:19)
    at new Constructor (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/utils.js:85:19)
    at IncomingMessage.<anonymous> (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:286:23)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  type: undefined,
  stack: 'Error: Invalid JSON received from the AmazonMws API\n    at Constructor._Error (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/Error.js:12:19)\n    at Constructor (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/utils.js:85:19)\n    at new Constructor (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/utils.js:85:19)\n    at IncomingMessage.<anonymous> (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:286:23)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  rawType: undefined,
  code: undefined,
  param: undefined,
  message: 'Invalid JSON received from the AmazonMws API',
  detail: undefined,
  raw:
   { message: 'Invalid JSON received from the AmazonMws API',
     response: '',
     exception: TypeError: Cannot read property 'toLowerCase' of undefined
    at processResponseType (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:181:75)
    at IncomingMessage.<anonymous> (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:219:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) } }
```

There should be a proper catch added to handle MWS server errors.

**Comment by bhushankumarl** [comment]
@colinskow Can you please provide sample API request that you are doing?

**Comment by bhushankumarl** [comment]
@colinskow 
Corrected in https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.19
