### ISSUE TITLE
GetFeedSubmissionResult: error parsing response

### ISSUE THREAD

**Issue by colinskow** [bhushankumarl/amazon-mws#65]
This is a result for a `_POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_` feed. I submitted the command exactly per the example in the README.

It is probably best if you just return the text response without trying to parse it.

```
MWS:AmazonMwsResource params { host: 'mws-eu.amazonservices.com', port: '443', path: '/Feeds/2009-01-01?&Version=2009-01-01&Action=GetFeedSubmissionResult&SellerId=XXX&MWSAuthToken=aXXX&FeedSubmissionId=873376017828&AWSAccessKeyId=XXX&Timestamp=2018-10-24T07%3A05%3A47.706Z&SignatureVersion=2&SignatureMethod=HmacSHA256&Signature=XXX', method: 'GET', headers: { 'Content-Type': 'text/xml', 'Content-MD5': 'XetHVN5ukbNI7W0ibK4SLA==' } }  +0ms
  MWS:AmazonMwsResource self.body ''  +2ms
  MWS:AmazonMwsResource ----------- Received Response ------------- +1s
  MWS:AmazonMwsResource responseString  Feed Processing Summary:
        Number of records processed             2
        Number of records successful            2

 +6ms
  MWS:AmazonMwsResource contentType  text/plain +1ms
  MWS:AmazonMwsResource statusCode  200 +0ms
  MWS:AmazonMwsResource It is NON-XML Response, so considered it as CSV file +6ms
  MWS:AmazonMwsResource error  Error: Unexpected Error: column header mismatch expected: 1 columns got: 4
    at ParserStream.self.__transform (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:138:48)
    at ParserStream.__parseLineData [as __handleLine] (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:65:18)
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:90:22
    at asyncIterator (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/extended.js:13:17)
    at Function.asyncEach (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/extended.js:31:10)
    at ParserStream.__processRows (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:88:18)
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:186:34
    at headerHandler (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:157:13)
    at ParserStream.__parseLineData [as __handleLine] (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:82:20)
    at ParserStream.__processHeaders (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:168:18)
    at ParserStream._parseLine [as _parse] (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:182:26)
    at ParserStream._transform (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:221:18)
    at ParserStream.Transform._read (_stream_transform.js:186:10)
    at ParserStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5) +19ms
  MWS:AmazonMwsResource error  TypeError: Cannot read property 'ErrorResponse' of undefined
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:300:38
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:204:28
    at ParserStream.<anonymous> (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:165:26)
    at emitOne (events.js:121:20)
    at ParserStream.emit (events.js:211:7)
    at spreadArgs (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/extended.js:43:25)
    at ParserStream.emit (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:325:13)
    at ParserStream.self.__transform (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:138:34)
    at ParserStream.__parseLineData [as __handleLine] (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:65:18)
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:90:22
    at asyncIterator (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/extended.js:13:17)
    at Function.asyncEach (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/extended.js:31:10)
    at ParserStream.__processRows (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:88:18)
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:186:34
    at headerHandler (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:157:13)
    at ParserStream.__parseLineData [as __handleLine] (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:82:20) +1ms
/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:300
                        if (response.ErrorResponse) {
                                     ^

TypeError: Cannot read property 'ErrorResponse' of undefined
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:300:38
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:204:28
    at ParserStream.<anonymous> (/home/colin/localdev/ecommerce/ab-mws/node_modules/amazon-mws/lib/AmazonMwsResource.js:165:26)
    at emitOne (events.js:116:13)
    at ParserStream.emit (events.js:211:7)
    at spreadArgs (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/extended.js:43:25)
    at ParserStream.emit (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:325:13)
    at onwriteError (_stream_writable.js:412:12)
    at onwrite (_stream_writable.js:440:5)
    at ParserStream.afterTransform (_stream_transform.js:90:3)
    at /home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:223:21
    at ParserStream._parseLine [as _parse] (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:196:13)
    at ParserStream._transform (/home/colin/localdev/ecommerce/ab-mws/node_modules/fast-csv/lib/parser/parser_stream.js:221:18)
    at ParserStream.Transform._read (_stream_transform.js:186:10)
    at ParserStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
```

**Comment by bhushankumarl** [comment]
@colinskow 
#64
