### ISSUE TITLE
Key must be a buffer error

### ISSUE THREAD

**Issue by jaypozo** [bhushankumarl/amazon-mws#9]
Hi, I get this error when I try to use `orders.search`
```
error  TypeError: Key must be a buffer
    at new Hmac (crypto.js:117:16)
    at Object.createHmac (crypto.js:643:10)
    at Constructor._request (/home/jay/src/megabuildlab/mws-data-service/node_modules/amazon-mws/lib/AmazonMwsResource.js:331:47)
    at Constructor.<anonymous> (/home/jay/src/megabuildlab/mws-data-service/node_modules/amazon-mws/lib/AmazonMwsMethod.js:88:18)
    at Constructor.search (/home/jay/src/megabuildlab/mws-data-service/node_modules/amazon-mws/lib/AmazonMwsMethod.js:37:33)
```

**Comment by jaypozo** [comment]
Ah, nvm was my fault for not passing in the access key ID properly.

**Comment by bhushankumarl** [comment]
@jaypozo Let me know if you need further support on any APIs.
